package report

import (
	"bytes"
	_ "embed"
	"fmt"
	"os"
	"strings"
	"unicode/utf8"

	"github.com/go-pdf/fpdf"

	"antigravity-seo/internal/textutil"
)

// fontFamily is the embedded UTF-8 font used throughout the PDF report. It
// covers Latin and Japanese glyphs (M PLUS 1p, SIL OFL 1.1 licensed — see
// fonts/OFL.txt) so titles, descriptions, and issue text render correctly
// instead of the mojibake produced by fpdf's core "Arial" (Latin-1) font.
const fontFamily = "mplus1p"

//go:embed fonts/MPLUS1p-Regular.ttf
var fontRegularBytes []byte

//go:embed fonts/MPLUS1p-Bold.ttf
var fontBoldBytes []byte

// Brand color palette matching claude-seo enterprise A4 reports
var (
	colorNavy      = []int{30, 58, 95}    // #1e3a5f: primary brand headers, title bars
	colorDarkNavy  = []int{26, 26, 46}    // #1a1a2e: dark text, bold labels
	colorGold      = []int{184, 134, 11}  // #b8860b: accent stripe & highlights
	colorSuccess   = []int{45, 106, 79}   // #2d6a4f: pass / good health
	colorWarning   = []int{212, 116, 14}  // #d4740e: warning / needs improvement
	colorDanger    = []int{197, 48, 48}   // #c53030: critical failure
	colorLightBg   = []int{250, 249, 247} // #faf9f7: warm cream card background
	colorGrid      = []int{214, 211, 204} // #d6d3cc: card and table borders
	colorMuted     = []int{107, 114, 128} // #6b7280: secondary / muted text
	colorWhite     = []int{255, 255, 255} // #ffffff
	colorRowAlt    = []int{247, 248, 250} // #f7f8fa: subtle alternating table row
	colorBadgeInfo = []int{74, 85, 104}   // #4a5568: info / neutral badge
)

// PDFReviewResult represents post-generation quality review
type PDFReviewResult struct {
	Status    string `json:"status"` // "PASS" or "WARN"
	PageCount int    `json:"page_count"`
	SizeBytes int64  `json:"size_bytes"`
	Message   string `json:"message"`
}

// RenderNativePDF creates an enterprise A4 PDF report in pure Go, matching claude-seo styling.
func RenderNativePDF(data *AuditData, outputPath string) (*PDFReviewResult, error) {
	pdfBytes, err := RenderNativePDFBytes(data)
	if err != nil {
		return nil, err
	}

	if err := os.WriteFile(outputPath, pdfBytes, 0o644); err != nil {
		return nil, fmt.Errorf("saving PDF to %s: %w", outputPath, err)
	}

	fi, err := os.Stat(outputPath)
	var sizeBytes int64
	if err == nil {
		sizeBytes = fi.Size()
	}

	// Post-generation review
	review := &PDFReviewResult{
		Status:    "PASS",
		SizeBytes: sizeBytes,
		Message:   "PDF generated successfully with pure Go engine",
	}
	if sizeBytes < 1024 {
		review.Status = "WARN"
		review.Message = "Generated PDF file size is unexpectedly small"
	}

	return review, nil
}

// RenderNativePDFBytes compiles the AuditData into a standalone A4 PDF byte buffer
func RenderNativePDFBytes(data *AuditData) ([]byte, error) {
	// A4 portrait: 210 x 297 mm
	// Margins: Left=18mm, Top=22mm, Right=18mm, Bottom=25mm
	// Printable width = 210 - (18 * 2) = 174mm
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(18, 22, 18)
	pdf.SetAutoPageBreak(true, 25)
	pdf.AliasNbPages("{nb}")

	// Register the embedded Latin+Japanese font before any SetFont/AddPage call.
	pdf.AddUTF8FontFromBytes(fontFamily, "", fontRegularBytes)
	pdf.AddUTF8FontFromBytes(fontFamily, "B", fontBoldBytes)

	// Running header and footer
	pdf.SetHeaderFunc(func() {
		if pdf.PageNo() > 1 {
			pdf.SetFont(fontFamily, "B", 8)
			pdf.SetTextColor(colorNavy[0], colorNavy[1], colorNavy[2])
			pdf.SetXY(18, 12)
			pdf.Cell(80, 5, "ANTIGRAVITY SEO & GEO AUDIT REPORT")

			pdf.SetFont(fontFamily, "", 8)
			pdf.SetTextColor(colorMuted[0], colorMuted[1], colorMuted[2])
			pdf.SetXY(98, 12)
			pdf.CellFormat(94, 5, data.Host, "", 0, "R", false, 0, "")

			pdf.SetDrawColor(colorGrid[0], colorGrid[1], colorGrid[2])
			pdf.SetLineWidth(0.3)
			pdf.Line(18, 18, 192, 18)
		}
	})

	pdf.SetFooterFunc(func() {
		pdf.SetDrawColor(colorGrid[0], colorGrid[1], colorGrid[2])
		pdf.SetLineWidth(0.3)
		pdf.Line(18, 282, 192, 282)

		pdf.SetFont(fontFamily, "", 8)
		pdf.SetTextColor(colorMuted[0], colorMuted[1], colorMuted[2])
		pdf.SetXY(18, 284)
		pdf.Cell(60, 5, "Confidential — Generated by Antigravity SEO")

		pdf.SetXY(78, 284)
		pdf.CellFormat(54, 5, fmt.Sprintf("Page %d of {nb}", pdf.PageNo()), "", 0, "C", false, 0, "")

		pdf.SetXY(132, 284)
		pdf.CellFormat(60, 5, data.Host, "", 0, "R", false, 0, "")
	})

	pdf.AddPage()

	// ── 1. Header Banner (Navy with Gold Accent) ──
	drawHeaderBanner(pdf, data)

	// ── 2. Executive Scorecard & Health Summary ──
	drawExecutiveScorecard(pdf, data)

	// ── 3. Category Score Cards (4 columns) ──
	drawCategoryCards(pdf, data)

	// ── 4. Priority Action Items & Findings ──
	drawFindingsSection(pdf, data)

	// ── 5. Technical & Server Diagnostics ──
	drawTechnicalDiagnostics(pdf, data)

	// ── 6. Content, Schema & International Analysis ──
	drawContentAndSchemaDiagnostics(pdf, data)

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("rendering PDF document: %w", err)
	}

	return buf.Bytes(), nil
}

func drawHeaderBanner(pdf *fpdf.Fpdf, data *AuditData) {
	// Top Banner: Navy background (height 26mm)
	pdf.SetFillColor(colorNavy[0], colorNavy[1], colorNavy[2])
	pdf.Rect(18, 22, 174, 25, "F")

	// Gold accent line (height 1.8mm)
	pdf.SetFillColor(colorGold[0], colorGold[1], colorGold[2])
	pdf.Rect(18, 47, 174, 1.8, "F")

	// Title
	pdf.SetXY(22, 26)
	pdf.SetFont(fontFamily, "B", 15)
	pdf.SetTextColor(colorWhite[0], colorWhite[1], colorWhite[2])
	pdf.Cell(105, 7, "SEO & GEO AUDIT REPORT")

	// Subtitle: Target Host
	pdf.SetXY(22, 34)
	pdf.SetFont(fontFamily, "", 9)
	pdf.SetTextColor(220, 225, 235)
	pdf.Cell(105, 5, truncateString(data.URL, 55))

	// Right column in banner: Date & Engine
	pdf.SetFont(fontFamily, "", 8)
	pdf.SetTextColor(210, 215, 225)
	pdf.SetXY(120, 27)
	pdf.CellFormat(68, 4, fmt.Sprintf("Domain: %s", data.Host), "", 0, "R", false, 0, "")
	pdf.SetXY(120, 32)
	pdf.CellFormat(68, 4, fmt.Sprintf("Date: %s", data.GeneratedAt), "", 0, "R", false, 0, "")
	pdf.SetXY(120, 37)
	pdf.CellFormat(68, 4, "Engine: Go Native A4 Architecture", "", 0, "R", false, 0, "")

	pdf.SetY(52)
}

func drawExecutiveScorecard(pdf *fpdf.Fpdf, data *AuditData) {
	pdf.SetY(52)

	// Summary Card background
	pdf.SetFillColor(colorLightBg[0], colorLightBg[1], colorLightBg[2])
	pdf.SetDrawColor(colorGrid[0], colorGrid[1], colorGrid[2])
	pdf.SetLineWidth(0.4)
	pdf.RoundedRect(18, 52, 174, 30, 2.5, "1234", "FD")

	// Overall Score Badge Box (left side: 32mm wide)
	scoreCol := getScoreRGB(data.Scores.Overall)
	pdf.SetFillColor(scoreCol[0], scoreCol[1], scoreCol[2])
	pdf.RoundedRect(22, 55, 28, 24, 2, "1234", "F")

	// Score Number
	pdf.SetFont(fontFamily, "B", 18)
	pdf.SetTextColor(colorWhite[0], colorWhite[1], colorWhite[2])
	pdf.SetXY(22, 59)
	pdf.CellFormat(28, 7, fmt.Sprintf("%d", data.Scores.Overall), "", 0, "C", false, 0, "")

	pdf.SetFont(fontFamily, "", 7)
	pdf.SetTextColor(colorWhite[0], colorWhite[1], colorWhite[2])
	pdf.SetXY(22, 67)
	pdf.CellFormat(28, 4, "OUT OF 100", "", 0, "C", false, 0, "")

	// Status & Executive Narrative (middle and right)
	pdf.SetFont(fontFamily, "B", 11)
	pdf.SetTextColor(colorDarkNavy[0], colorDarkNavy[1], colorDarkNavy[2])
	pdf.SetXY(55, 56)
	pdf.Cell(90, 6, fmt.Sprintf("Executive Site Health: %s", getScoreGrade(data.Scores.Overall)))

	// Counts
	critCount, warnCount, passCount := countSeverities(data.Issues)
	pdf.SetFont(fontFamily, "", 9)
	pdf.SetTextColor(colorDarkNavy[0], colorDarkNavy[1], colorDarkNavy[2])
	pdf.SetXY(55, 63)
	summaryText := fmt.Sprintf(
		"Automated audit identified %d total findings: %d critical issues, %d warnings, and %d passing checks.",
		len(data.Issues), critCount, warnCount, passCount,
	)
	pdf.MultiCell(132, 4.5, summaryText, "", "L", false)

	pdf.SetY(85)
}

func drawCategoryCards(pdf *fpdf.Fpdf, data *AuditData) {
	pdf.SetY(85)

	// 4 Category Cards: 40.5mm wide each with 4mm gap = (40.5 * 4) + (4 * 3) = 162 + 12 = 174mm
	categories := []struct {
		Label  string
		Weight string
		Score  int
	}{
		{"Technical Health", "Weight: 30%", data.Scores.Technical},
		{"Structured Data", "Weight: 25%", data.Scores.Schema},
		{"Content & E-E-A-T", "Weight: 25%", data.Scores.Content},
		{"Media & Assets", "Weight: 20%", data.Scores.Media},
	}

	cardW := 40.5
	cardH := 23.0
	gap := 4.0
	startX := 18.0
	y := 85.0

	for i, cat := range categories {
		x := startX + float64(i)*(cardW+gap)

		// Card Box
		pdf.SetFillColor(colorLightBg[0], colorLightBg[1], colorLightBg[2])
		pdf.SetDrawColor(colorGrid[0], colorGrid[1], colorGrid[2])
		pdf.SetLineWidth(0.3)
		pdf.RoundedRect(x, y, cardW, cardH, 2.0, "1234", "FD")

		// Top accent line colored by category score
		scCol := getScoreRGB(cat.Score)
		pdf.SetFillColor(scCol[0], scCol[1], scCol[2])
		pdf.Rect(x, y, cardW, 1.5, "F")

		// Category Label
		pdf.SetFont(fontFamily, "B", 8)
		pdf.SetTextColor(colorDarkNavy[0], colorDarkNavy[1], colorDarkNavy[2])
		pdf.SetXY(x+2, y+3)
		pdf.Cell(cardW-4, 4, cat.Label)

		// Weight
		pdf.SetFont(fontFamily, "", 6.5)
		pdf.SetTextColor(colorMuted[0], colorMuted[1], colorMuted[2])
		pdf.SetXY(x+2, y+7)
		pdf.Cell(cardW-4, 3.5, cat.Weight)

		// Score number
		pdf.SetFont(fontFamily, "B", 13)
		pdf.SetTextColor(scCol[0], scCol[1], scCol[2])
		pdf.SetXY(x+2, y+11)
		pdf.Cell(cardW-4, 6, fmt.Sprintf("%d", cat.Score))

		// Rating tag
		pdf.SetFont(fontFamily, "B", 6.5)
		pdf.SetXY(x+2, y+17)
		pdf.Cell(cardW-4, 4, getScoreBadgeLabel(cat.Score))
	}

	pdf.SetY(112)
}

func drawFindingsSection(pdf *fpdf.Fpdf, data *AuditData) {
	ensureSpace(pdf, 30)
	drawSectionTitle(pdf, "Priority Issues & Action Items")

	if len(data.Issues) == 0 {
		pdf.SetFont(fontFamily, "", 9)
		pdf.SetTextColor(colorMuted[0], colorMuted[1], colorMuted[2])
		pdf.Cell(174, 8, "No outstanding issues identified on audited pages.")
		pdf.Ln(10)
		return
	}

	// Table Header
	pdf.SetFillColor(colorNavy[0], colorNavy[1], colorNavy[2])
	pdf.SetTextColor(colorWhite[0], colorWhite[1], colorWhite[2])
	pdf.SetFont(fontFamily, "B", 8)
	pdf.CellFormat(22, 6, "SEVERITY", "", 0, "C", true, 0, "")
	pdf.CellFormat(28, 6, "CATEGORY", "", 0, "L", true, 0, "")
	pdf.CellFormat(124, 6, "FINDING & ACTIONABLE RECOMMENDATION", "", 1, "L", true, 0, "")

	// Table Rows
	for i, iss := range data.Issues {
		ensureSpace(pdf, 14)

		isAlt := i%2 == 1
		if isAlt {
			pdf.SetFillColor(colorRowAlt[0], colorRowAlt[1], colorRowAlt[2])
		} else {
			pdf.SetFillColor(colorWhite[0], colorWhite[1], colorWhite[2])
		}

		startY := pdf.GetY()
		badgeCol := getSeverityRGB(iss.Severity)

		// Severity Badge
		pdf.SetFillColor(badgeCol[0], badgeCol[1], badgeCol[2])
		pdf.RoundedRect(19, startY+1.2, 20, 4.5, 1.2, "1234", "F")

		pdf.SetFont(fontFamily, "B", 6.5)
		pdf.SetTextColor(colorWhite[0], colorWhite[1], colorWhite[2])
		pdf.SetXY(19, startY+1.2)
		pdf.CellFormat(20, 4.5, string(iss.Severity), "", 0, "C", false, 0, "")

		// Category
		pdf.SetXY(40, startY)
		pdf.SetFont(fontFamily, "B", 7.5)
		pdf.SetTextColor(colorNavy[0], colorNavy[1], colorNavy[2])
		pdf.Cell(28, 5, iss.Category)

		// Finding Description & Recommendation
		pdf.SetXY(68, startY)
		pdf.SetFont(fontFamily, "", 7.5)
		pdf.SetTextColor(colorDarkNavy[0], colorDarkNavy[1], colorDarkNavy[2])

		combinedMsg := iss.Message
		if iss.Recommendation != "" {
			combinedMsg += " — Fix: " + iss.Recommendation
		}
		pdf.MultiCell(124, 4, combinedMsg, "", "L", false)

		// Draw subtle bottom separator
		endY := pdf.GetY()
		pdf.SetDrawColor(colorGrid[0], colorGrid[1], colorGrid[2])
		pdf.SetLineWidth(0.2)
		pdf.Line(18, endY+1, 192, endY+1)
		pdf.SetY(endY + 2)
	}

	pdf.Ln(4)
}

func drawTechnicalDiagnostics(pdf *fpdf.Fpdf, data *AuditData) {
	ensureSpace(pdf, 50)
	drawSectionTitle(pdf, "Technical & Server Diagnostics")

	type DiagRow struct {
		Label string
		Value string
		Note  string
	}

	statusStr := "—"
	protocolStr := "—"
	ttfbStr := "—"
	if data.Headers != nil {
		statusStr = fmt.Sprintf("%d HTTP", data.Headers.StatusCode)
		if data.Headers.Server != "" {
			protocolStr = data.Headers.Server
		}
		ttfbStr = fmt.Sprintf("%d ms", data.Headers.TTFBMS)
	}

	titleStr := "—"
	descStr := "—"
	canonicalStr := "—"
	robotsStr := "—"
	descLimits := textutil.MetaDescLimitsFor(textutil.Latin)
	if data.Technical != nil {
		titleStr = fmt.Sprintf("%s (%d chars, %d units)", data.Technical.Title, utf8.RuneCountInString(data.Technical.Title), data.Technical.TitleWidth)
		descStr = fmt.Sprintf("%s (%d chars, %d units)", data.Technical.MetaDescription, utf8.RuneCountInString(data.Technical.MetaDescription), data.Technical.MetaDescWidth)
		descLimits = textutil.MetaDescLimitsFor(textutil.ParseScript(data.Technical.Script))
		if data.Technical.Canonical != "" {
			canonicalStr = data.Technical.Canonical
		}
		if data.Technical.MetaRobots != "" {
			robotsStr = data.Technical.MetaRobots
		}
	}

	rows := []DiagRow{
		{"HTTP Response", statusStr, protocolStr},
		{"TTFB (Latency)", ttfbStr, "Time to First Byte"},
		{"Canonical Tag", truncateString(canonicalStr, 48), "Target URL definition"},
		{"Robots Directives", robotsStr, "Meta robots / X-Robots-Tag"},
		{"Page Title", truncateString(titleStr, 52), fmt.Sprintf("Target width: %d-%d units (CJK = 2)", textutil.TitleLimits.Min, textutil.TitleLimits.Max)},
		{"Meta Description", truncateString(descStr, 52), fmt.Sprintf("Target width: %d-%d units (CJK = 2)", descLimits.Min, descLimits.Max)},
	}

	// Two-column diagnostic key-values
	pdf.SetFillColor(colorNavy[0], colorNavy[1], colorNavy[2])
	pdf.SetTextColor(colorWhite[0], colorWhite[1], colorWhite[2])
	pdf.SetFont(fontFamily, "B", 8)
	pdf.CellFormat(40, 5.5, "METRIC", "", 0, "L", true, 0, "")
	pdf.CellFormat(85, 5.5, "OBSERVED VALUE", "", 0, "L", true, 0, "")
	pdf.CellFormat(49, 5.5, "BENCHMARK / CONTEXT", "", 1, "L", true, 0, "")

	for i, r := range rows {
		ensureSpace(pdf, 7)
		if i%2 == 1 {
			pdf.SetFillColor(colorRowAlt[0], colorRowAlt[1], colorRowAlt[2])
		} else {
			pdf.SetFillColor(colorWhite[0], colorWhite[1], colorWhite[2])
		}

		pdf.SetFont(fontFamily, "B", 7.5)
		pdf.SetTextColor(colorDarkNavy[0], colorDarkNavy[1], colorDarkNavy[2])
		pdf.CellFormat(40, 5, r.Label, "B", 0, "L", true, 0, "")

		pdf.SetFont(fontFamily, "", 7.5)
		pdf.CellFormat(85, 5, r.Value, "B", 0, "L", true, 0, "")

		pdf.SetFont(fontFamily, "", 7)
		pdf.SetTextColor(colorMuted[0], colorMuted[1], colorMuted[2])
		pdf.CellFormat(49, 5, r.Note, "B", 1, "L", true, 0, "")
	}

	pdf.Ln(4)
}

func drawContentAndSchemaDiagnostics(pdf *fpdf.Fpdf, data *AuditData) {
	ensureSpace(pdf, 50)
	drawSectionTitle(pdf, "Content, Schema & International Analysis")

	wordCountStr := "—"
	readingTimeStr := "—"
	headingsStr := "—"
	if data.Content != nil {
		wordCountStr = fmt.Sprintf("%d words", data.Content.WordCount)
		readingTimeStr = fmt.Sprintf("%d min read (%d paragraphs)", data.Content.ReadingTimeMin, data.Content.ParagraphCount)
	}
	if data.Technical != nil {
		headingsStr = fmt.Sprintf("H1: %d | H2: %d | H3: %d", data.Technical.H1Count, data.Technical.H2Count, data.Technical.H3Count)
	}

	schemaStr := "None detected"
	if data.Schema != nil && len(data.Schema.Blocks) > 0 {
		types := []string{}
		for _, b := range data.Schema.Blocks {
			types = append(types, b.Types...)
		}
		schemaStr = fmt.Sprintf("%d blocks: %s", len(data.Schema.Blocks), strings.Join(types, ", "))
	}

	imageStr := "—"
	if data.Images != nil {
		altPct := 0
		if data.Images.TotalImages > 0 {
			altPct = ((data.Images.TotalImages - data.Images.MissingAlt) * 100) / data.Images.TotalImages
		}
		imageStr = fmt.Sprintf("%d total (%d missing alt, %d%% coverage)", data.Images.TotalImages, data.Images.MissingAlt, altPct)
	}

	hreflangStr := "None detected"
	if data.Hreflang != nil && data.Hreflang.Count > 0 {
		hreflangStr = fmt.Sprintf("%d alternate link(s)", data.Hreflang.Count)
	}

	items := []struct {
		Label string
		Value string
	}{
		{"Content Length", wordCountStr},
		{"Reading Time", readingTimeStr},
		{"Heading Structure", headingsStr},
		{"Image Alt Coverage", imageStr},
		{"Structured Data (JSON-LD)", truncateString(schemaStr, 70)},
		{"International Hreflang", hreflangStr},
	}

	pdf.SetFillColor(colorNavy[0], colorNavy[1], colorNavy[2])
	pdf.SetTextColor(colorWhite[0], colorWhite[1], colorWhite[2])
	pdf.SetFont(fontFamily, "B", 8)
	pdf.CellFormat(50, 5.5, "EVALUATION CRITERIA", "", 0, "L", true, 0, "")
	pdf.CellFormat(124, 5.5, "RESULT & SYNTHESIS", "", 1, "L", true, 0, "")

	for i, item := range items {
		ensureSpace(pdf, 7)
		if i%2 == 1 {
			pdf.SetFillColor(colorRowAlt[0], colorRowAlt[1], colorRowAlt[2])
		} else {
			pdf.SetFillColor(colorWhite[0], colorWhite[1], colorWhite[2])
		}

		pdf.SetFont(fontFamily, "B", 7.5)
		pdf.SetTextColor(colorDarkNavy[0], colorDarkNavy[1], colorDarkNavy[2])
		pdf.CellFormat(50, 5, item.Label, "B", 0, "L", true, 0, "")

		pdf.SetFont(fontFamily, "", 7.5)
		pdf.CellFormat(124, 5, item.Value, "B", 1, "L", true, 0, "")
	}

	pdf.Ln(6)
}

func drawSectionTitle(pdf *fpdf.Fpdf, title string) {
	pdf.SetFillColor(colorNavy[0], colorNavy[1], colorNavy[2])
	pdf.Rect(18, pdf.GetY(), 3, 6, "F") // accent stripe on left

	pdf.SetFont(fontFamily, "B", 10.5)
	pdf.SetTextColor(colorNavy[0], colorNavy[1], colorNavy[2])
	pdf.SetXY(23, pdf.GetY())
	pdf.Cell(169, 6, title)
	pdf.Ln(8)
}

func ensureSpace(pdf *fpdf.Fpdf, neededMM float64) {
	if pdf.GetY()+neededMM > 275 {
		pdf.AddPage()
	}
}

func getScoreRGB(score int) []int {
	if score >= 80 {
		return colorSuccess
	}
	if score >= 50 {
		return colorWarning
	}
	return colorDanger
}

func getSeverityRGB(sev IssueSeverity) []int {
	switch sev {
	case SeverityCritical:
		return colorDanger
	case SeverityWarning:
		return colorWarning
	case SeverityPass:
		return colorSuccess
	default:
		return colorBadgeInfo
	}
}

func getScoreGrade(score int) string {
	if score >= 90 {
		return "EXCELLENT (A+)"
	}
	if score >= 80 {
		return "GOOD (PASSING)"
	}
	if score >= 65 {
		return "FAIR (NEEDS WORK)"
	}
	if score >= 50 {
		return "POOR (AT RISK)"
	}
	return "CRITICAL (DEFICIENT)"
}

func getScoreBadgeLabel(score int) string {
	if score >= 80 {
		return "GOOD"
	}
	if score >= 50 {
		return "NEEDS WORK"
	}
	return "POOR"
}

func countSeverities(issues []Issue) (crit, warn, pass int) {
	for _, iss := range issues {
		switch iss.Severity {
		case SeverityCritical:
			crit++
		case SeverityWarning:
			warn++
		case SeverityPass:
			pass++
		}
	}
	return
}

// truncateString shortens s to at most maxLen runes, appending "..." when
// truncated. It operates on runes (not bytes) so multi-byte UTF-8 sequences
// (e.g. Japanese text) are never split mid-character.
func truncateString(s string, maxLen int) string {
	r := []rune(s)
	if len(r) <= maxLen {
		return s
	}
	if maxLen <= 3 {
		return string(r[:maxLen])
	}
	return string(r[:maxLen-3]) + "..."
}
